name = "mindmap-agent"
main = "src/worker.js"
compatibility_date = "2024-01-15"

[env.production]
name = "mindmap-agent"

[env.staging]
name = "mindmap-agent"

# 环境变量
[vars]
NODE_ENV = "production"

# 密钥（需要在Cloudflare Dashboard中设置）
# DEEPSEEK_API_KEY